version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules_volume:/app/blog/node_modules
    tty: true
    # command: sh -c "cd blog && npm install && npm run dev"
    # SSG確認用のbuild&start
    command: sh -c "cd blog && npm run build && npm run start"
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3001:3000
volumes:
  node_modules_volume: